// google font 
import { Roboto_Condensed } from "next/font/google";
// global css
import "./globals.css";
// components
import { Header } from "./_components/Header";
import Footer from "./_components/Footer";
// chakra ui
import { ChakraProvider } from "@chakra-ui/react";

const inter = Roboto_Condensed({ subsets: ["latin"] });

export const metadata = {
  title: "Appscrip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Header />
          {children}
          <Footer/>
        </ChakraProvider>
          
      </body>
    </html>
  );
}
